name: Docker Image CI

on:
  schedule:
    - cron: "5 * * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose -v 
